### PR TITLE
support tox 3.8.0

### PR DESCRIPTION
**Pull request by gaborbernat**
We should use action.popen instead of subprocess while there 👍 Resolves #30

### CODE REVIEW

**Comment by rpkilby** [comment]
Hi @gaborbernat - while the project has shared ownership under the tox org, I am the original author, so please give me at least some time to review non-trivial PRs before merging them into master. Obviously, if I've died or become inactive, that's one thing, but I just committed to this repo last night and haven't otherwise removed myself from maintenance. 

A few other notes:
- Please don't merge failing PRs. I know Travis is currently having some capacity issues, but please wait to merge until those builds pass. 
- Please keep PRs focused to a single feature. e.g., black and pre-commit are not related to the issue and don't need to be included in the PR. 
- On black, I actually have a strong dislike for it and will not use it on any project I own. Please do not add it in the future. I think the existing linters are Good Enough<sup>TM</sup>.
- On pre-commit, I haven't used it, but it doesn't seem necessary for a project this small. Again, the linter setup & CI are good enough.

----

Please don't take this too critically. Obviously, you've done a lot of great work in advancing tox's development this past year or so. But, when it comes to other author's plugins, at least give them a little time to react and provide feedback.

**Comment by rpkilby** [comment]
Instead of issuing a revert (which will trigger CI), I'm just removing the commit from master. 

edit: Apparently it didn't matter - the force update triggered the build anyway. Oh well.

**Comment by gaborbernat** [comment]
@rpkilby feel free to cherry-pick the other changes 👍

**Comment by rpkilby** [comment]
@gaborbernat - thanks again for the fix.

**Comment by rpkilby** [comment]
Hey - I just noticed the addition of `redirect` to `venv._pcall`. What does this argument do? I briefly looked at the `action` source code, and my guess is that it's redirecting the stream output to a file, but am confused by using the verbosity check to set the argument.

**Comment by gaborbernat** [comment]
If it's verbose enough will print to stdout instead of redirect 👍

**Comment by rpkilby** [comment]
Sorry - wasn't clear. I understand how verbosity affects the flag. I'm just not sure what `redirect` does in the action class. What is redirected and where is redirected to? Is it stdout to a log file?

**Comment by gaborbernat** [comment]
Yes, rather than kept onto the stdout 👍

**Pull request merged**
